### ISSUE TITLE
About function context_window()

### ISSUE THREAD

**Issue by Joefi** [mravanelli/pytorch-kaldi#118]
Hi,  I'm little confused about the function context_window() in data_io.py, I think this function may take frames of other sentences as the left or right context of current frame of current sentence, because of roll operation. 
here is the function context_window in data_io.py
`def context_window(fea,left,right)\:
 
    N_elem=fea.shape[0]
    N_fea=fea.shape[1]
    
    fea_conc=np.empty([N_elem,N_fea*(left+right+1)])
    
    index_fea=0
    for lag in range(-left,right+1):
        fea_conc[:,index_fea:index_fea+fea.shape[1]]=np.roll(fea,lag,axis=0)
        index_fea=index_fea+fea.shape[1]
        
    fea_conc=fea_conc[left:fea_conc.shape[0]-right]
    
    return fea_conc
`
Look forward to your reply.

**Comment by mravanelli** [comment]
Yes, the current implementation works at matrix level and might take some frames of the other sentences at the beginning and end of each sentence. Note that in most of the cases the initial and final frames of each sentence are silences and what you actually include are most of the time just silence frames for the other sentences. We implemented it because it is more efficient that doing the operation at sentence level and adding zeros.

**Comment by Joefi** [comment]
Thank you reply, I get it.
