### ISSUE TITLE
size mismatch for wx.0.weight  when running  python run_exp.py cfg/TIMIT_baselines/TIMIT_GRU_mfcc.cfg

### ISSUE THREAD

**Issue by PeiyanFlying** [mravanelli/pytorch-kaldi#121]
When I begin run this command, I get the error like this:
<img width="1305" alt="Screen Shot 2019-07-05 at 5 41 16 PM" src="https://user-images.githubusercontent.com/45463777/60746345-48d8a800-9f4c-11e9-8e07-a196474b2c86.png">
Please how to solve this problem? Many thanks!

**Comment by PeiyanFlying** [comment]
This is my corresponding cfg:
[cfg_proto]
cfg_proto = proto/global.proto
cfg_proto_chunk = proto/global_chunk.proto


[exp]
cmd =
run_nn_script = run_nn
out_folder = exp/TIMIT_GRU_mfcc
seed = 2234
use_cuda = True
multi_gpu = False
save_gpumem = False
n_epochs_tr = 24


[dataset1]
data_name = TIMIT_tr
fea = fea_name=mfcc
	fea_lst=/home/dongpe/kaldi/egs/timit/s5/data/train/feats.scp
	fea_opts=apply-cmvn --utt2spk=ark:/home/dongpe/kaldi/egs/timit/s5/data/train/utt2spk  ark:/home/dongpe/kaldi/egs/timit/s5/mfcc/cmvn_train.ark ark:- ark:- | add-deltas --delta-order=2 ark:- ark:- |
	cw_left=0
	cw_right=0

	fea_name=fbank
	fea_lst=/home/dongpe/kaldi/egs/timit/s5/data/train/feats.scp
	fea_opts=apply-cmvn --utt2spk=ark:/home/dongpe/kaldi/egs/timit/s5/data/train/utt2spk  ark:home/dongpe/kaldi/egs/timit/s5/mfcc/cmvn_train.ark ark:- ark:- | add-deltas --delta-order=0 ark:- ark:- |
	cw_left=0
	cw_right=0

	fea_name=fmllr
	fea_lst=/home/dongpe/kaldi/egs/timit/s5/data/train/feats.scp
	fea_opts=apply-cmvn --utt2spk=ark:/home/dongpe/kaldi/egs/timit/s5/data/train/utt2spk  ark:home/dongpe/kaldi/egs/timit/s5/mfcc/cmvn_train.ark ark:- ark:- | add-deltas --delta-order=0 ark:- ark:- |
	cw_left=0
	cw_right=0
lab = lab_name=lab_cd
	lab_folder=/home/dongpe/kaldi/egs/timit/s5/exp/tri3_ali
	lab_opts=ali-to-pdf
	lab_count_file=auto
	lab_data_folder=/home/dongpe/kaldi/egs/timit/s5/data/train/
	lab_graph=/home/dongpe/kaldi/egs/timit/s5/exp/tri3/graph

	lab_name=lab_mono
	lab_folder=/home/dongpe/kaldi/egs/timit/s5/exp/tri3_ali
	lab_opts=ali-to-phones --per-frame=true
	lab_count_file=none
	lab_data_folder=/home/dongpe/kaldi/egs/timit/s5/data/train/
	lab_graph=home/dongpe/kaldi/egs/timit/s5/exp/tri3/graph
n_chunks = 5


[dataset2]
data_name = TIMIT_dev
fea = fea_name=mfcc
	fea_lst=/home/dongpe/kaldi/egs/timit/s5/data/dev/feats.scp
	fea_opts=apply-cmvn --utt2spk=ark:/home/dongpe/kaldi/egs/timit/s5/data/dev/utt2spk  ark:/home/dongpe/kaldi/egs/timit/s5/mfcc/cmvn_dev.ark ark:- ark:- | add-deltas --delta-order=2 ark:- ark:- |
	cw_left=0
	cw_right=0

	fea_name=fbank
	fea_lst=/home/dongpe/kaldi/egs/timit/s5/data/dev/feats.scp
	fea_opts=apply-cmvn --utt2spk=ark:/home/dongpe/kaldi/egs/timit/s5/data/dev/utt2spk  ark:/home/dongpe/kaldi/egs/timit/s5/mfcc/cmvn_dev.ark ark:- ark:- | add-deltas --delta-order=0 ark:- ark:- |
	cw_left=0
	cw_right=0

	fea_name=fmllr
	fea_lst=/home/dongpe/kaldi/egs/timit/s5/data/dev/feats.scp
	fea_opts=apply-cmvn --utt2spk=ark:/home/dongpe/kaldi/egs/timit/s5/data/dev/utt2spk  ark:/home/dongpe/kaldi/egs/timit/s5/mfcc/cmvn_dev.ark ark:- ark:- | add-deltas --delta-order=0 ark:- ark:- |
	cw_left=0
	cw_right=0
lab = lab_name=lab_cd
	lab_folder=/home/dongpe/kaldi/egs/timit/s5/mfcc/cmvn_dev.ark
	lab_opts=ali-to-pdf
	lab_count_file=auto
	lab_data_folder=/home/dongpe/kaldi/egs/timit/s5/data/dev
	lab_graph=/home/dongpe/kaldi/egs/timit/s5/exp/tri3/graph

	lab_name=lab_mono
	lab_folder=/home/dongpe/kaldi/egs/timit/s5/mfcc/cmvn_dev.ark
	lab_opts=ali-to-phones --per-frame=true
	lab_count_file=none
	lab_data_folder=/home/dongpe/kaldi/egs/timit/s5/mfcc/cmvn_dev.ark
	lab_graph=q/home/dongpe/kaldi/egs/timit/s5/exp/tri3/graph
n_chunks = 1


[dataset3]
data_name = TIMIT_test
fea = fea_name=mfcc
	fea_lst=/home/dongpe/kaldi/egs/timit/s5/data/test/feats.scp
	fea_opts=apply-cmvn --utt2spk=ark:/home/dongpe/kaldi/egs/timit/s5/data/test/utt2spk  ark:/home/dongpe/kaldi/egs/timit/s5/mfcc/cmvn_test.ark ark:- ark:- | add-deltas --delta-order=2 ark:- ark:- |
	cw_left=0
	cw_right=0

	fea_name=fbank
	fea_lst=/home/dongpe/kaldi/egs/timit/s5/data/test/feats.scp
	fea_opts=apply-cmvn --utt2spk=ark:/home/dongpe/kaldi/egs/timit/s5/data/test/utt2spk  ark:/home/dongpe/kaldi/egs/timit/s5/mfcc/cmvn_test.ark ark:- ark:- | add-deltas --delta-order=0 ark:- ark:- |
	cw_left=0
	cw_right=0

	fea_name=fmllr
	fea_lst=/home/dongpe/kaldi/egs/timit/s5/data/test/feats.scp
	fea_opts=apply-cmvn --utt2spk=ark:/home/dongpe/kaldi/egs/timit/s5/data/test/utt2spk  ark:/home/dongpe/kaldi/egs/timit/s5/mfcc/cmvn_test.ark ark:- ark:- | add-deltas --delta-order=0 ark:- ark:- |
	cw_left=0
	cw_right=0
lab = lab_name=lab_cd
	lab_folder=/home/dongpe/kaldi/egs/timit/s5/exp/tri3_ali_test
	lab_opts=ali-to-pdf
	lab_count_file=auto
	lab_data_folder=/home/dongpe/kaldi/egs/timit/s5/data/test
	lab_graph=/home/dongpe/kaldi/egs/timit/s5/exp/tri3/graph

	lab_name=lab_mono
	lab_folder=/home/dongpe/kaldi/egs/timit/s5/exp/tri3_ali_test
	lab_opts=ali-to-phones --per-frame=true
	lab_count_file=none
	lab_data_folder=/home/dongpe/kaldi/egs/timit/s5/data/test
	lab_graph=/home/dongpe/kaldi/egs/timit/s5/exp/tri3/graph
n_chunks = 1


[data_use]
train_with = TIMIT_tr
valid_with = TIMIT_dev
forward_with = TIMIT_test


[batches]
batch_size_train = 8
max_seq_length_train = 1000
increase_seq_length_train = True
start_seq_len_train = 100
multply_factor_seq_len_train = 2
batch_size_valid = 8
max_seq_length_valid = 1000


[architecture1]
arch_name = GRU_layers
arch_proto = proto/GRU.proto
arch_library = neural_networks
arch_class = GRU
arch_pretrain_file = none
arch_freeze = False
arch_seq_model = True
gru_lay = 550,550,550,550,550
gru_drop = 0.2,0.2,0.2,0.2,0.2
gru_use_laynorm_inp = False
gru_use_batchnorm_inp = False
gru_use_laynorm = False,False,False,False,False
gru_use_batchnorm = True,True,True,True,True
gru_bidir = True
gru_act = tanh,tanh,tanh,tanh,tanh
gru_orthinit = True
arch_lr = 0.0004
arch_halving_factor = 0.5
arch_improvement_threshold = 0.001
arch_opt = rmsprop
opt_momentum = 0.0
opt_alpha = 0.95
opt_eps = 1e-8
opt_centered = False
opt_weight_decay = 0.0


[architecture2]
arch_name = MLP_layers
arch_proto = proto/MLP.proto
arch_library = neural_networks
arch_class = MLP
arch_pretrain_file = none
arch_freeze = False
arch_seq_model = False
dnn_lay = N_out_lab_cd
dnn_drop = 0.0
dnn_use_laynorm_inp = False
dnn_use_batchnorm_inp = False
dnn_use_batchnorm = False
dnn_use_laynorm = False
dnn_act = softmax
arch_lr = 0.0004
arch_halving_factor = 0.5
arch_improvement_threshold = 0.001
arch_opt = rmsprop
opt_momentum = 0.0
opt_alpha = 0.95
opt_eps = 1e-8
opt_centered = False
opt_weight_decay = 0.0


[architecture3]
arch_name = MLP_layers2
arch_proto = proto/MLP.proto
arch_library = neural_networks
arch_class = MLP
arch_pretrain_file = none
arch_freeze = False
arch_seq_model = False
dnn_lay = N_out_lab_mono
dnn_drop = 0.0
dnn_use_laynorm_inp = False
dnn_use_batchnorm_inp = False
dnn_use_batchnorm = False
dnn_use_laynorm = False
dnn_act = softmax
arch_lr = 0.0004
arch_halving_factor = 0.5
arch_improvement_threshold = 0.001
arch_opt = rmsprop
opt_momentum = 0.0
opt_alpha = 0.95
opt_eps = 1e-8
opt_centered = False
opt_weight_decay = 0.0


[model]
model_proto = proto/model.proto
model = out_dnn1=compute(GRU_layers,mfcc)
	out_dnn2=compute(MLP_layers,out_dnn1)
	out_dnn3=compute(MLP_layers2,out_dnn1)
	loss_mono=cost_nll(out_dnn3,lab_mono)
	loss_mono_w=mult_constant(loss_mono,1.0)
	loss_cd=cost_nll(out_dnn2,lab_cd)
	loss_final=sum(loss_cd,loss_mono_w)
	err_final=cost_err(out_dnn2,lab_cd)


[forward]
forward_out = out_dnn2
normalize_posteriors = True
normalize_with_counts_from = lab_cd
save_out_file = False
require_decoding = True


[decoding]
decoding_script_folder = kaldi_decoding_scripts/
decoding_script = decode_dnn.sh
decoding_proto = proto/decoding.proto
min_active = 200
max_active = 7000
max_mem = 50000000
beam = 13.0
latbeam = 8.0
acwt = 0.2
max_arcs = -1
skip_scoring = false
scoring_script = local/score.sh
scoring_opts = "--min-lmwt 1 --max-lmwt 10"
norm_vars = False

**Comment by mravanelli** [comment]
It seems you have stored an old version of the model and you are using it.
Could you try do delete the exp_file folder and restart the experiment?

Mirco

**Comment by Mrmoore98** [comment]
I met same error, when I was ran the TIMIT_liGRU_mfcc.cfg. I deleted exp file and the error was still there.  I think the problem is in the kaldi's feature extraction step. however i'm not familiar with kaldi and the tutorial example in pytorch-kaldi is simple so please help me to sovle this! Thanks!!
What I have done :
run.sh(in egs/timit/s5, added four lines to generate fbank feature )
`fbankdir=fbank
for x in train dev test; do
  steps/make_fbank.sh --cmd "$train_cmd" --nj $feats_nj data/$x exp/make_fbank/$x $fankdir
  steps/compute_cmvn_stats.sh data/$x exp/make_fbank/$x $fbankdir
done`
/local/nnet/run_dnn.sh
then 
the 5 line aligment commands provided by tutorial

and used compute_cvmn.sh modify the data-fmllr-tri3.
`feadir=fmllr-tri3
for x in train dev test; do
  steps/compute_cmvn_stats.sh data/$x data-fmllr-tri3/$x $feadir
done`
Here is my cfg:
`[cfg_proto]
cfg_proto = proto/global.proto
cfg_proto_chunk = proto/global_chunk.proto

[exp]
cmd = 
run_nn_script = run_nn
out_folder = exp/TIMIT_liGRU_mfcc
seed = 2234
use_cuda = True
multi_gpu = False
save_gpumem = False
n_epochs_tr = 24

[dataset1]
data_name = TIMIT_tr
fea = fea_name=mfcc
	fea_lst=/home/niexing/projects/kaldi/egs/timit/s5/data/train/feats.scp
	fea_opts=apply-cmvn --utt2spk=ark:/home/niexing/projects/kaldi/egs/timit/s5/data/train/utt2spk  ark:/home/niexing/projects/kaldi/egs/timit/s5/mfcc/cmvn_train.ark ark:- ark:- | add-deltas --delta-order=2 ark:- ark:- |
	cw_left=0
	cw_right=0
	
	fea_name=fbank
	fea_lst=/home/niexing/projects/kaldi/egs/timit/s5/data/train/feats.scp
	fea_opts=apply-cmvn --utt2spk=ark:/home/niexing/projects/kaldi/egs/timit/s5/data/train/utt2spk  ark:/home/niexing/projects/kaldi/egs/timit/s5/fbank/cmvn_train.ark ark:- ark:- | add-deltas --delta-order=0 ark:- ark:- |
	cw_left=0
	cw_right=0
	
	fea_name=fmllr
	fea_lst=/home/niexing/projects/kaldi/egs/timit/s5/data-fmllr-tri3/train/feats.scp
	fea_opts=apply-cmvn --utt2spk=ark:/home/niexing/projects/kaldi/egs/timit/s5/data/train/utt2spk  ark:/home/niexing/projects/kaldi/egs/timit/s5/fmllr-tri3/train_cmvn.ark ark:- ark:- | add-deltas --delta-order=0 ark:- ark:- |
	cw_left=0
	cw_right=0
lab = lab_name=lab_cd
	lab_folder=/home/niexing/projects/kaldi/egs/timit/s5/exp/dnn4_pretrain-dbn_dnn_ali
	lab_opts=ali-to-pdf
	lab_count_file=auto
	lab_data_folder=/home/niexing/projects/kaldi/egs/timit/s5/data/train/
	lab_graph=/home/niexing/projects/kaldi/egs/timit/s5/exp/tri3/graph
	
	lab_name=lab_mono
	lab_folder=/home/niexing/projects/kaldi/egs/timit/s5/exp/dnn4_pretrain-dbn_dnn_ali
	lab_opts=ali-to-phones --per-frame=true
	lab_count_file=none
	lab_data_folder=/home/niexing/projects/kaldi/egs/timit/s5/data/train/
	lab_graph=/home/niexing/projects/kaldi/egs/timit/s5/exp/tri3/graph
n_chunks = 5

[dataset2]
data_name = TIMIT_dev
fea = fea_name=mfcc
	fea_lst=/home/niexing/projects/kaldi/egs/timit/s5/data/dev/feats.scp
	fea_opts=apply-cmvn --utt2spk=ark:/home/niexing/projects/kaldi/egs/timit/s5/data/dev/utt2spk  ark:/home/niexing/projects/kaldi/egs/timit/s5/mfcc/cmvn_dev.ark ark:- ark:- | add-deltas --delta-order=2 ark:- ark:- |
	cw_left=5
	cw_right=5
	
	fea_name=fbank
	fea_lst=/home/niexing/projects/kaldi/egs/timit/s5/data/dev/feats.scp
	fea_opts=apply-cmvn --utt2spk=ark:/home/niexing/projects/kaldi/egs/timit/s5/data/dev/utt2spk  ark:/home/niexing/projects/kaldi/egs/timit/s5/fbank/cmvn_dev.ark ark:- ark:- | add-deltas --delta-order=0 ark:- ark:- |
	cw_left=0
	cw_right=0
	
	fea_name=fmllr
	fea_lst=/home/niexing/projects/kaldi/egs/timit/s5/data-fmllr-tri3/dev/feats.scp
	fea_opts=apply-cmvn --utt2spk=ark:/home/niexing/projects/kaldi/egs/timit/s5/data/dev/utt2spk  ark:/home/niexing/projects/kaldi/egs/timit/s5/fmllr-tri3/dev_cmvn.ark ark:- ark:- | add-deltas --delta-order=0 ark:- ark:- |
	cw_left=0
	cw_right=0
lab = lab_name=lab_cd
	lab_folder=/home/niexing/projects/kaldi/egs/timit/s5/exp/dnn4_pretrain-dbn_dnn_ali_dev
	lab_opts=ali-to-pdf
	lab_count_file=auto
	lab_data_folder=/home/niexing/projects/kaldi/egs/timit/s5/data/dev/
	lab_graph=/home/niexing/projects/kaldi/egs/timit/s5/exp/tri3/graph

	
	lab_name=lab_mono
	lab_folder=/home/niexing/projects/kaldi/egs/timit/s5/exp/dnn4_pretrain-dbn_dnn_ali_dev
	lab_opts=ali-to-phones --per-frame=true
	lab_count_file=none
	lab_data_folder=/home/niexing/projects/kaldi/egs/timit/s5/data/dev/
	lab_graph=/home/niexing/projects/kaldi/egs/timit/s5/exp/tri3/graph
n_chunks = 1

[dataset3]
data_name = TIMIT_test
fea = fea_name=mfcc
	fea_lst=/home/niexing/projects/kaldi/egs/timit/s5/data/test/feats.scp
	fea_opts=apply-cmvn --utt2spk=ark:/home/niexing/projects/kaldi/egs/timit/s5/data/test/utt2spk  ark:/home/niexing/projects/kaldi/egs/timit/s5/mfcc/cmvn_test.ark ark:- ark:- | add-deltas --delta-order=2 ark:- ark:- |
	cw_left=5
	cw_right=5
	
	fea_name=fbank
	fea_lst=/home/niexing/projects/kaldi/egs/timit/s5/data/test/feats.scp
	fea_opts=apply-cmvn --utt2spk=ark:/home/niexing/projects/kaldi/egs/timit/s5/data/test/utt2spk  ark:/home/niexing/projects/kaldi/egs/timit/s5/fbank/cmvn_test.ark ark:- ark:- | add-deltas --delta-order=0 ark:- ark:- |
	cw_left=0
	cw_right=0
	
	fea_name=fmllr
	fea_lst=/home/niexing/projects/kaldi/egs/timit/s5/data-fmllr-tri3/test/feats.scp
	fea_opts=apply-cmvn --utt2spk=ark:/home/niexing/projects/kaldi/egs/timit/s5/data/test/utt2spk  ark:/home/niexing/projects/kaldi/egs/timit/s5/fmllr-tri3/test_cmvn.ark ark:- ark:- | add-deltas --delta-order=0 ark:- ark:- |
	cw_left=0
	cw_right=0
lab = lab_name=lab_cd
	lab_folder=/home/niexing/projects/kaldi/egs/timit/s5/exp/dnn4_pretrain-dbn_dnn_ali_test
	lab_opts=ali-to-pdf
	lab_count_file=auto
	lab_data_folder=/home/niexing/projects/kaldi/egs/timit/s5/data/test/
	lab_graph=/home/niexing/projects/kaldi/egs/timit/s5/exp/tri3/graph
	
	lab_name=lab_mono
	lab_folder=/home/niexing/projects/kaldi/egs/timit/s5/exp/dnn4_pretrain-dbn_dnn_ali_test
	lab_opts=ali-to-phones --per-frame=true
	lab_count_file=none
	lab_data_folder=/home/niexing/projects/kaldi/egs/timit/s5/data/test/
	lab_graph=/home/niexing/projects/kaldi/egs/timit/s5/exp/tri3/graph
n_chunks = 1

[data_use]
train_with = TIMIT_tr
valid_with = TIMIT_dev
forward_with = TIMIT_test

[batches]
batch_size_train = 8
max_seq_length_train = 1000
increase_seq_length_train = True
start_seq_len_train = 100
multply_factor_seq_len_train = 2
batch_size_valid = 8
max_seq_length_valid = 1000

[architecture1]
arch_name = liGRU_layers
arch_proto = proto/liGRU.proto
arch_library = neural_networks
arch_class = liGRU
arch_pretrain_file = none
arch_freeze = False
arch_seq_model = True
ligru_lay = 550,550,550,550,550
ligru_drop = 0.2,0.2,0.2,0.2,0.2
ligru_use_laynorm_inp = False
ligru_use_batchnorm_inp = False
ligru_use_laynorm = False,False,False,False,False
ligru_use_batchnorm = True,True,True,True,True
ligru_bidir = True
ligru_act = relu,relu,relu,relu,relu
ligru_orthinit = True
arch_lr = 0.0004
arch_halving_factor = 0.5
arch_improvement_threshold = 0.001
arch_opt = rmsprop
opt_momentum = 0.0
opt_alpha = 0.95
opt_eps = 1e-8
opt_centered = False
opt_weight_decay = 0.0

[architecture2]
arch_name = MLP_layers
arch_proto = proto/MLP.proto
arch_library = neural_networks
arch_class = MLP
arch_pretrain_file = none
arch_freeze = False
arch_seq_model = False
dnn_lay = N_out_lab_cd
dnn_drop = 0.0
dnn_use_laynorm_inp = False
dnn_use_batchnorm_inp = False
dnn_use_batchnorm = False
dnn_use_laynorm = False
dnn_act = softmax
arch_lr = 0.0004
arch_halving_factor = 0.5
arch_improvement_threshold = 0.001
arch_opt = rmsprop
opt_momentum = 0.0
opt_alpha = 0.95
opt_eps = 1e-8
opt_centered = False
opt_weight_decay = 0.0

[architecture3]
arch_name = MLP_layers2
arch_proto = proto/MLP.proto
arch_library = neural_networks
arch_class = MLP
arch_pretrain_file = none
arch_freeze = False
arch_seq_model = False
dnn_lay = N_out_lab_mono
dnn_drop = 0.0
dnn_use_laynorm_inp = False
dnn_use_batchnorm_inp = False
dnn_use_batchnorm = False
dnn_use_laynorm = False
dnn_act = softmax
arch_lr = 0.0004
arch_halving_factor = 0.5
arch_improvement_threshold = 0.001
arch_opt = rmsprop
opt_momentum = 0.0
opt_alpha = 0.95
opt_eps = 1e-8
opt_centered = False
opt_weight_decay = 0.0

[model]
model_proto = proto/model.proto
model = out_dnn1=compute(liGRU_layers,mfcc)
	out_dnn2=compute(MLP_layers,out_dnn1)
	out_dnn3=compute(MLP_layers2,out_dnn1)
	loss_mono=cost_nll(out_dnn3,lab_mono)
	loss_mono_w=mult_constant(loss_mono,1.0)
	loss_cd=cost_nll(out_dnn2,lab_cd)
	loss_final=sum(loss_cd,loss_mono_w)
	err_final=cost_err(out_dnn2,lab_cd)

[forward]
forward_out = out_dnn2
normalize_posteriors = True
normalize_with_counts_from = lab_cd
save_out_file = False
require_decoding = True

[decoding]
decoding_script_folder = kaldi_decoding_scripts/
decoding_script = decode_dnn.sh
decoding_proto = proto/decoding.proto
min_active = 200
max_active = 7000
max_mem = 50000000
beam = 13.0
latbeam = 8.0
acwt = 0.2
max_arcs = -1
skip_scoring = false
scoring_script = local/score.sh
scoring_opts = "--min-lmwt 1 --max-lmwt 10"
norm_vars = False

` 

Problem I met
`(asr) niexing@gpu:~/projects/pytorch-kaldi$ python run_exp.py cfg/TIMIT_baselines/TIMIT_liGRU_mfcc.cfg
- Reading config file......OK!
- Chunk creation......OK!

------------------------------ Epoch 00 / 23 ------------------------------
Training TIMIT_tr chunk = 2 / 5
[========================================] 100% Training | (Batch 306/306)) | L:5.491
Training TIMIT_tr chunk = 3 / 5
[========================================] 100% Training | (Batch 302/302)) | L:4.579
Training TIMIT_tr chunk = 4 / 5
[========================================] 100% Training | (Batch 305/305)) | L:4.168
Training TIMIT_tr chunk = 5 / 5
OMP: Warning #190: Forking a process while a parallel region is active is potentially unsafe.
[========================================] 100% Training | (Batch 304/304)) | L:3.769
Validating TIMIT_dev chunk = 1 / 1
Traceback (most recent call last):
  File "run_exp.py", line 264, in <module>
    [data_name,data_set,data_end_index,fea_dict,lab_dict,arch_dict]=run_nn(data_name,data_set,data_end_index,fea_dict,lab_dict,arch_dict,config_chunk_file,processed_first,next_conf                  ig_file)
  File "/home/niexing/projects/pytorch-kaldi/core.py", line 391, in run_nn
    nns[net].load_state_dict(checkpoint_load['model_par'])
  File "/home/niexing/anaconda3/envs/asr/lib/python3.7/site-packages/torch/nn/modules/module.py", line 769, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for liGRU:
        size mismatch for wh.0.weight: copying a param with shape torch.Size([550, 69]) from checkpoint, the shape in current model is torch.Size([550, 759]).
        size mismatch for wz.0.weight: copying a param with shape torch.Size([550, 69]) from checkpoint, the shape in current model is torch.Size([550, 759]).
`

@mravanelli  , @TParcollet

**Comment by TParcollet** [comment]
Hi,

Please mind the fact that you're not training on fbanks but on MFCC here: 
model = out_dnn1=compute(liGRU_layers,mfcc)

This line calls the liGRU_layers on the mfcc features declared before.

**Comment by Mrmoore98** [comment]
Hi,
Do you mean fbank and fmllr features are redundancy in this cfg file?

**Comment by Mrmoore98** [comment]
However, I still don't know how to solve my problem. if latter two feature does not involve with process then what caused the model size mismatch( in training stage first input_dim = 69, input_dim=759 in test ).
@TParcollet

**Comment by TParcollet** [comment]
Ok so:

Under the [dataset] section, you can define any number of features you want. In your CFG you have MFCC, FBANK and FMLLR. NONETHELESS, it does not mean that you will use all these features, the only feature that is important is the one (or the combination) that you pass to: 
`model = out_dnn1=compute(liGRU_layers,mfcc)`
in this case, it's MFCC. In this case, you will only load the mfcc features as input features, with respect to the description of these features you gave into your different [datasets]. If you want to use fbank, you must replace mfcc by fbank in this line. The error might be caused by the fact that the MFCC features for the validation are wrongly generated.

**Comment by Mrmoore98** [comment]
Ok I will regenerate mfcc feature

Thank for your help !!!!

**Comment by TParcollet** [comment]
Once re-generated. Please check that in your feats.scp for each data (train,dev,test) you only path linking to mfcc files (mfcc in the name).

**Comment by Mrmoore98** [comment]
You mean I need to modify run.sh in kaldi to generate feats.scp with mfcc name, in the tutorial the mfcc fea_lst path is the data file (like data/train/feats.scp)?  

I'm really confused with these setting, please excuse my dumb questions.

**Comment by TParcollet** [comment]
No, the feats.scp is generated when you call make_mfcc / make_fbank etc. The problem is that, when you call make_mfcc, and then make_fbank, the feat.scp of make_mfcc is replaced with the one of make_fbank (and thus contain paths to fbank). Just generate mfccs features for {train, dev, test) and lauch pytorch-kaldi again on MFCC features

**Comment by Mrmoore98** [comment]
Ok, i start to understand what the problem is.

When I need multiple feature  ( like TIMIT_DNN_liGRU_DNN_mfcc+fbank+fmllr.cfg), then i need to create two data path for mfcc and fbank respectively?

**Comment by TParcollet** [comment]
yes :)

**Comment by Mrmoore98** [comment]
@TParcollet  I re-generated feats.scp, and the problem still there. However, using same feats.scp, cfg/TIMIT_MLP_mfcc_basic.cfg is work.


  
Validating TIMIT_dev chunk = 1 / 1
OMP: Warning #190: Forking a process while a parallel region is active is potentially unsafe.
Traceback (most recent call last):
  File "run_exp.py", line 264, in <module>
    [data_name,data_set,data_end_index,fea_dict,lab_dict,arch_dict]=run_nn(data_name,data_set,data_end_index,fea_dict,lab_dict,arch_dict,config_chunk_file,processed_first,next_config_file)
  File "/home/niexing/projects/pytorch-kaldi/core.py", line 392, in run_nn
    nns[net].load_state_dict(checkpoint_load['model_par'])
  File "/home/niexing/anaconda3/envs/asr/lib/python3.7/site-packages/torch/nn/modules/module.py", line 769, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for liGRU:
        size mismatch for wh.0.weight: copying a param with shape torch.Size([550, 39]) from checkpoint, the shape in current model is torch.Size([550, 429]).
        size mismatch for wz.0.weight: copying a param with shape torch.Size([550, 39]) from checkpoint, the shape in current model is torch.Size([550, 429]).
