### ISSUE TITLE
Issue in the decode period.

### ISSUE THREAD

**Issue by chijiudao** [mravanelli/pytorch-kaldi#186]
Hi. 
There are some issue in the  decode period.  After finished, no WER present. 
![(1)](https://user-images.githubusercontent.com/39076097/69618760-629e9700-1075-11ea-9d78-c80973295580.png)
The log is here:
![（2）](https://user-images.githubusercontent.com/39076097/69619758-0e94b200-1077-11ea-84d3-67f06f8d2d8d.jpg)
 While the feats.scp exists. Could you give me suggestions?  Thx!

**Comment by chijiudao** [comment]
The exp is TIMIT_CNN_raw.cfg.   I get the feats_raw.scp use save_raw_fea.py.     These files are stored in the raw_TIMIT_200ms/dev ,/train ,/test.     And the .ark files in the folder. Maybe i need to copy the glm and text files from timit/s5/data/test to raw_TIMIT_200ms/test?

**Comment by mravanelli** [comment]
Hi,
could you try to replace raw_TIMIT_200ms/test/feats.scp with its absolute path?

**Comment by chijiudao** [comment]
Thank you for your reply！ Yes，I have set the alsolute parh。

**Comment by chijiudao** [comment]
![traindataset](https://user-images.githubusercontent.com/39076097/69686555-185ff900-10fb-11ea-88ec-a0e952f151a2.png)
![devdataset](https://user-images.githubusercontent.com/39076097/69686566-1e55da00-10fb-11ea-8498-94a7b3d6d201.png)
![testdataset](https://user-images.githubusercontent.com/39076097/69686571-231a8e00-10fb-11ea-859a-1252c6b6f734.png)

**Comment by mravanelli** [comment]
The error is caused by the following lines of the decode_nn.sh

# Some checks.  Note: we don't need $srcdir/tree but we expect
# it should exist, given the current structure of the scripts.
for f in $graphdir/HCLG.fst $data/feats.scp; do
  [ ! -f $f ] && echo "$0: no such file $f" && exit 1;
done

To solve the issue you have to set up the lab_data_folder of your config
file with an absolute path.
The decoding script runs within the kaldi_decoding_scirpts (and not within
pytorch-kaldi) folder and if you set a relative path, it raises and error.

Please, let me know if this solves the problem.

Best,

Mirco

**Comment by chijiudao** [comment]
Yes! The pronlem has solved with your suggestion. Thank you！
