### ISSUE TITLE
About hmm-info error

### ISSUE THREAD

**Issue by Subohao** [mravanelli/pytorch-kaldi#193]
Hello, sir,
I'm following the instruction in the ReadMe file,
after finishing using dnn alignments of dnn in TIMIT example corpus,
I encounter a error as below:
ERROR: hmm-info command doesn't exist. Make sure your .bashrc contains the Kaldi paths and correctly exports it.

Then, I checked the hmm-info in the terminal and it really has been installed.
I finally traced the code in utils.py line #621 and I try to directly type the command on the terminal to read the final.mdl in my "s5/exp/dnn4_pretrain-dbn_dnn_ali" directory, and the result is as below:

ZOE WARNING (from hmm-info): zoeHMM aborting (header)
ZOE ERROR (from hmm-info): zoeGetHMM failed to parse /home/borris/Disk_D/BIIC/kaldi/egs/timit/s5/exp/dnn4_pretrain-dbn_dnn_ali/final.mdl
ZOE library version 2013-02-16 

I think the error is due to nothing been generated after I use the command  hmm-info "MY_MODEL_DIR" instead of not installing hmm-info.
Do you have any suggestion to fix the error message, please help me with this when you are free.

p.s. there is no error when training the dnn model on the TIMIT corpus by kaldi, and also no error message while running the instruction in the ReadMe below:

steps/nnet/align.sh --nj 4 data-fmllr-tri3/train data/lang exp/dnn4_pretrain-dbn_dnn exp/dnn4_pretrain-dbn_dnn_ali

steps/nnet/align.sh --nj 4 data-fmllr-tri3/dev data/lang exp/dnn4_pretrain-dbn_dnn exp/dnn4_pretrain-dbn_dnn_ali_dev

steps/nnet/align.sh --nj 4 data-fmllr-tri3/test data/lang exp/dnn4_pretrain-dbn_dnn exp/dnn4_pretrain-dbn_dnn_ali_test

**Comment by TParcollet** [comment]
Hi ! 

Could you please give us information on what is the "Zoe" prefix exactly ?

**Comment by Subohao** [comment]
I'm not quite sure what is "Zoe" prefix, 
but I remember at the first time the error was that I didn't install hmm-info, 
so it suggest me to install SNAP on ubuntu, and then I follow the instruction.
I think this is the package I installed.
https://manpages.ubuntu.com/manpages/bionic/man1/hmm-info.1.html

**Comment by TParcollet** [comment]
wait hmm-info is just a standard Kaldi binary. You should just source this binary in your path?

**Comment by Subohao** [comment]
Ohh.... I got it, because I install SANP package and it just replace the kaldi binary.
The code is working after I remove SNAP.
Thank you so much!!!

**Comment by mnabihali** [comment]
Sorry I have the same problem
ERROR: hmm-info command doesn't exist. Make sure your .bashrc contains the Kaldi paths and correctly exports it.
can you explain what is the solution

**Comment by mravanelli** [comment]
Hi,
this error is due to the fact that the hmm-info executable (compiled during
the kaldi installation doesn't exist). What happen if you type hmm-info in
a bash shell?
You should see something like this:

(base) mirco@mirco:~$ hmm-info
hmm-info

Write to standard output various properties of HMM-based transition model
Usage:  hmm-info [options] <model-in>
e.g.:
 hmm-info trans.mdl

Standard options:
  --config                    : Configuration file to read (this option may
be repeated) (string, default = "")
  --help                      : Print out usage message (bool, default =
false)
  --print-args                : Print the command line arguments (to
stderr) (bool, default = true)
  --verbose                   : Verbose level (higher->more logging) (int,
default = 0)

If not, make sure kaldi is installed and you have kaldi paths in your
.bashrc file (see prerequisites section in the documentation)

Best,

Mirco

**Comment by mnabihali** [comment]
Dear Mirco
Thanks,
Because I am new at Kaldi so, the (.bashrc file) is the path.sh file in the s5 folder in timit
