### ISSUE TITLE
Is there Conv2d CNN demo for neural_network.py ?

### ISSUE THREAD

**Issue by lezasantaizi** [mravanelli/pytorch-kaldi#205]
rt

**Comment by mravanelli** [comment]
We are implementing 2D convolutional neural networks for the speechbrain project, but in pytorch-kaldi are not natively implemented. It should be easy to include them. Personally, I'm not a big fan on 2-D CNNs for processing speech because according to my experience I never saw improvements with that.

**Comment by lezasantaizi** [comment]
OK, Thank you for your reply ! I get it ~
