### ISSUE TITLE
Cannot get WER when running TIMIT_SincNet_raw experiment

### ISSUE THREAD

**Issue by zehaitu** [mravanelli/pytorch-kaldi#211]
Hi,

I am trying to run the TIMIT_SincNet_raw experiment, but wers returned in the DECODING part is blank. Could you please help me with this, what could cause this problem? 

Many thanks

**Comment by TParcollet** [comment]
Hey ! 
Could you please post a screenshot of this phenomenon? Thanks!

**Comment by XMarusic** [comment]
The best way to find out the issue is to look the log.log file in your output folder. If there is an issue while decoding, the error will probably be mentioned at EOF. 

If there in no error, then look into your decode folder. there are different files, like wer* or logs inside scoring folder that will probably give you some more details.
