### ISSUE TITLE
TIMIT sample problem

### ISSUE THREAD

**Issue by 873765272** [mravanelli/pytorch-kaldi#38]
TIMIT sample problem
After following the instructions step by step installation, I received an error when running python run_exp.py cfg/TIMIT_baselines/TIMIT_MLP_mfcc_basic.cfg as follows.

Traceback (most recent call last):
   File "run_exp.py", line 49, in <module>
     [config,name_data,name_arch]=check_cfg(cfg_file,config,cfg_file_proto)
   File "/home/chen/pytorch-kaldi/utils.py", line 565, in check_cfg
     N_out=int(output.decode().rstrip())
ValueError: invalid literal for int() with base 10: ''

Can you tell me the reason for the error and how to modify it?

**Comment by TParcollet** [comment]
Hi ! It's likely that the script wasn't able to retrieve the number of output labels from the hmm. Since this retrieval is based on the cmd 'hmm-info' could you please give us the output of:
'hmm-info /path/to/your/final.mdl ? ' 
With TIMIT, the final.mdl can be found in  exp/dnn4_pretrain_dbn_dnn if you used the DNN alignements from the recipe or exp/tri3 if not.

**Comment by mravanelli** [comment]
does this solved the problem?
