### ISSUE TITLE
How to use pytorch-kaldi for Speaker REcognition (SRE) ?

### ISSUE THREAD

**Issue by tonytonyissaissa** [mravanelli/pytorch-kaldi#52]
Hi,
Thank you very much for this interesting project.
I am wondering if it is possible to use pytprch-kaldi for speaker recognition. If yes, could you please give me some hints and clues on how to start ? is there any tutorial for this ?

Thanks in advance,
Tony

**Comment by mravanelli** [comment]
Hi Tony,
thank you very much for your interest into the pytorch-kaldi project. In
the near future, we would like to evolve pytorch-kaldi in order to make it
more suitable for other tasks, such as speaker recognition, command
recognition, speech enhancement, and speech separation. The current
version, in fact, is suitable for speech recognition experiments only. For
speaker identification you can meanwhile take a look into the SincNEt
repository here: https://github.com/mravanelli/SincNet

I will keep you updated!

Best,

Mirco

**Comment by tonytonyissaissa** [comment]
Thank you for this quick reply!
It is a pleasure to know that you have a plan to add speaker recognition and other speech tasks to pytorch-kaldi.
Kind regards,
Tony
