### ISSUE TITLE
System Configuration

### ISSUE THREAD

**Issue by gerardgilliland** [mravanelli/pytorch-kaldi#88]
I apologize for posting under issues -- it's the best I could find.
I need help with a system configuration.
I have an Android app BirdingViaMic that records bird song and attempts to recognize the birds from their songs.
I am only using pitch, timing, and (poorly) modified Mel-frequency cepstral coefficients.
I want to learn speech recognition and apply it to the recordings.
What I know is I need a Graphics Processing Unit (GPU)
What I need to know is two things: (really five things)
What Computer Hardware (Make/Model), Operating system (Version), and Language do I need to run pytorch-kaldi?
I have a Intel Windows 10 system with no extra slots, and a 32GB Unix based Raspberry Pi. Neither have a GPU. 
I assume I need a new system.
What Site(s), book, course, can I go to to learn enough so I can come back here and be able to understand and attempt what you are doing? 
A third question might not be answerable:
Google can recognize speech on my Android phone with an online system or you can download a language and use it offline. 
I would eventually like to be able to do that. Is that possible?
Thank you and Peace,
Gerard Gilliland
gerardg@modelsw.com

**Comment by TParcollet** [comment]
Hi,

First of all, you should better ask to some more specialized place like Reddit. Nonetheless, I can give you some answers. 

1) You need a GPU only if the model you use is medium sized or big. A simple 3 layers neural network can be trained with a CPU. It also depends on the amount of data you have. But I would recommend buying a GPU with enough VRAM for your need.

2) Computer Hardware: It depends on your needs. 8 Cores + 32Go of RAM and a GPU are enough to start working with Kaldi on some serious datasets. You can check Ryzen processors that are cheaper. Ofc you also need enough storage space for your dataset.

3) Operating System: Linux latest stable version. I have no experience on kaldi with Windows, it might be troublesome. 

4) Language: Pytorch-Kaldi need you to only learn python and pytorch. The framework handle all the Kaldi stuffs for the users. NONETHELESS, your application is quite specific and I would recommend also learning kaldi that will help you with custom systems.

5) If you are truly new to speech recognition, you will have to find ressources to learn the basics. To start using Pytorch-Kaldi, you only need knowledge on neural networks for speech recognition, since the framework hide the Kaldi parts. 

6) What you are trying to do is known as speaker identification. Unless you trully want to try to transcribe what the birds are "saying" ? If you only need to identify which type of bird, then it's speaker identification, and Pytorch-Kaldi is not ready yet for this task. Nonetheless, you can easily adapt it once you have enough python knowledge. 

When you design your own speech recognition model with Pytorch-kaldi or Kaldi, you are already doing "offline" speech recognition, since the models and ressources are local. Nonetheless, embedding this in a smartphone can be very very hard, due to the power needed to infer and process the datas... 

Titouan.

**Comment by mravanelli** [comment]
Hi,
this application is interesting (in part similar to the works currently
done by Vincent Lostanlen, that I met some days ago in NY).
As said by Titouan, I think that your classification task is more similar
to speaker-identification rather than speaker recognition. You might want
to take a look into this repository:
https://github.com/mravanelli/SincNet
This repository contains only the SincNet model and it is much easier to
adapt to your task of interest.

Keep us updated!

Best,

Mirco

**Comment by gerardgilliland** [comment]
@mravanelli and @TParcollet,
Thank you for your quick response,
for taking the time in answering my questions in full, and within my comprehension,
and for your perspective on the possible work ahead if I get far enough to attempt a transfer of the work to an Android.
I watched the excellent YouTube Video "A brief Introduction to SincNet."
You are both correct in clarifying I need "speaker identification."
I am comfortable with Python3, and Linux.
I discovered that the Raspberry Pi has a GPU.
I am going to attempt to run the speaker id experiment.
If it fails to run I will look into more hardware.
If it runs, I will follow with "How to use SincNet with a different dataset."
I will be back with an update (and more questions) somewhere in the above list.
Thank you and Peace,
Gerard

**Comment by ahmedbhna** [comment]
Thanks for sharing the pytorch kaldi repo. I have one question. how can i use my own data ?

**Comment by mravanelli** [comment]
Dear Ahmed,
you can find this information on the documentation here:

https://github.com/mravanelli/pytorch-kaldi#how-can-i-use-my-own-dataset

Best,

Mirco


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
